/* eslint-disable */
/* tslint:disable */
/**
 * This is an autogenerated file created by the Stencil compiler.
 * It contains typing information for all components that exist in this project.
 */
import { HTMLStencilElement, JSXBase } from "@stencil/core/internal";
export namespace Components {
    interface DeAlert {
        /**
          * @default 'Alert'
         */
        "heading": string;
    }
    interface DeAlertShadow {
        /**
          * @default 'Alert'
         */
        "heading": string;
    }
    interface DeButton {
        /**
          * @default 'md'
         */
        "size": 'sm' | 'md' | 'lg';
    }
    interface DeButtonShadow {
        /**
          * @default 'md'
         */
        "size": 'sm' | 'md' | 'lg';
    }
}
export interface DeButtonCustomEvent<T> extends CustomEvent<T> {
    detail: T;
    target: HTMLDeButtonElement;
}
declare global {
    interface HTMLDeAlertElement extends Components.DeAlert, HTMLStencilElement {
    }
    var HTMLDeAlertElement: {
        prototype: HTMLDeAlertElement;
        new (): HTMLDeAlertElement;
    };
    interface HTMLDeAlertShadowElement extends Components.DeAlertShadow, HTMLStencilElement {
    }
    var HTMLDeAlertShadowElement: {
        prototype: HTMLDeAlertShadowElement;
        new (): HTMLDeAlertShadowElement;
    };
    interface HTMLDeButtonElementEventMap {
        "tripleClick": MouseEvent;
    }
    interface HTMLDeButtonElement extends Components.DeButton, HTMLStencilElement {
        addEventListener<K extends keyof HTMLDeButtonElementEventMap>(type: K, listener: (this: HTMLDeButtonElement, ev: DeButtonCustomEvent<HTMLDeButtonElementEventMap[K]>) => any, options?: boolean | AddEventListenerOptions): void;
        addEventListener<K extends keyof DocumentEventMap>(type: K, listener: (this: Document, ev: DocumentEventMap[K]) => any, options?: boolean | AddEventListenerOptions): void;
        addEventListener<K extends keyof HTMLElementEventMap>(type: K, listener: (this: HTMLElement, ev: HTMLElementEventMap[K]) => any, options?: boolean | AddEventListenerOptions): void;
        addEventListener(type: string, listener: EventListenerOrEventListenerObject, options?: boolean | AddEventListenerOptions): void;
        removeEventListener<K extends keyof HTMLDeButtonElementEventMap>(type: K, listener: (this: HTMLDeButtonElement, ev: DeButtonCustomEvent<HTMLDeButtonElementEventMap[K]>) => any, options?: boolean | EventListenerOptions): void;
        removeEventListener<K extends keyof DocumentEventMap>(type: K, listener: (this: Document, ev: DocumentEventMap[K]) => any, options?: boolean | EventListenerOptions): void;
        removeEventListener<K extends keyof HTMLElementEventMap>(type: K, listener: (this: HTMLElement, ev: HTMLElementEventMap[K]) => any, options?: boolean | EventListenerOptions): void;
        removeEventListener(type: string, listener: EventListenerOrEventListenerObject, options?: boolean | EventListenerOptions): void;
    }
    var HTMLDeButtonElement: {
        prototype: HTMLDeButtonElement;
        new (): HTMLDeButtonElement;
    };
    interface HTMLDeButtonShadowElement extends Components.DeButtonShadow, HTMLStencilElement {
    }
    var HTMLDeButtonShadowElement: {
        prototype: HTMLDeButtonShadowElement;
        new (): HTMLDeButtonShadowElement;
    };
    interface HTMLElementTagNameMap {
        "de-alert": HTMLDeAlertElement;
        "de-alert-shadow": HTMLDeAlertShadowElement;
        "de-button": HTMLDeButtonElement;
        "de-button-shadow": HTMLDeButtonShadowElement;
    }
}
declare namespace LocalJSX {
    interface DeAlert {
        /**
          * @default 'Alert'
         */
        "heading"?: string;
    }
    interface DeAlertShadow {
        /**
          * @default 'Alert'
         */
        "heading"?: string;
    }
    interface DeButton {
        "onTripleClick"?: (event: DeButtonCustomEvent<MouseEvent>) => void;
        /**
          * @default 'md'
         */
        "size"?: 'sm' | 'md' | 'lg';
    }
    interface DeButtonShadow {
        /**
          * @default 'md'
         */
        "size"?: 'sm' | 'md' | 'lg';
    }

    interface DeAlertAttributes {
        "heading": string;
    }
    interface DeAlertShadowAttributes {
        "heading": string;
    }
    interface DeButtonAttributes {
        "size": 'sm' | 'md' | 'lg';
    }
    interface DeButtonShadowAttributes {
        "size": 'sm' | 'md' | 'lg';
    }

    interface IntrinsicElements {
        "de-alert": Omit<DeAlert, keyof DeAlertAttributes> & { [K in keyof DeAlert & keyof DeAlertAttributes]?: DeAlert[K] } & { [K in keyof DeAlert & keyof DeAlertAttributes as `attr:${K}`]?: DeAlertAttributes[K] } & { [K in keyof DeAlert & keyof DeAlertAttributes as `prop:${K}`]?: DeAlert[K] };
        "de-alert-shadow": Omit<DeAlertShadow, keyof DeAlertShadowAttributes> & { [K in keyof DeAlertShadow & keyof DeAlertShadowAttributes]?: DeAlertShadow[K] } & { [K in keyof DeAlertShadow & keyof DeAlertShadowAttributes as `attr:${K}`]?: DeAlertShadowAttributes[K] } & { [K in keyof DeAlertShadow & keyof DeAlertShadowAttributes as `prop:${K}`]?: DeAlertShadow[K] };
        "de-button": Omit<DeButton, keyof DeButtonAttributes> & { [K in keyof DeButton & keyof DeButtonAttributes]?: DeButton[K] } & { [K in keyof DeButton & keyof DeButtonAttributes as `attr:${K}`]?: DeButtonAttributes[K] } & { [K in keyof DeButton & keyof DeButtonAttributes as `prop:${K}`]?: DeButton[K] };
        "de-button-shadow": Omit<DeButtonShadow, keyof DeButtonShadowAttributes> & { [K in keyof DeButtonShadow & keyof DeButtonShadowAttributes]?: DeButtonShadow[K] } & { [K in keyof DeButtonShadow & keyof DeButtonShadowAttributes as `attr:${K}`]?: DeButtonShadowAttributes[K] } & { [K in keyof DeButtonShadow & keyof DeButtonShadowAttributes as `prop:${K}`]?: DeButtonShadow[K] };
    }
}
export { LocalJSX as JSX };
declare module "@stencil/core" {
    export namespace JSX {
        interface IntrinsicElements {
            "de-alert": LocalJSX.IntrinsicElements["de-alert"] & JSXBase.HTMLAttributes<HTMLDeAlertElement>;
            "de-alert-shadow": LocalJSX.IntrinsicElements["de-alert-shadow"] & JSXBase.HTMLAttributes<HTMLDeAlertShadowElement>;
            "de-button": LocalJSX.IntrinsicElements["de-button"] & JSXBase.HTMLAttributes<HTMLDeButtonElement>;
            "de-button-shadow": LocalJSX.IntrinsicElements["de-button-shadow"] & JSXBase.HTMLAttributes<HTMLDeButtonShadowElement>;
        }
    }
}
