/* eslint-disable */
/* tslint:disable */
/**
 * This is an autogenerated file created by the Stencil compiler.
 * It contains typing information for all components that exist in this project.
 */
import { HTMLStencilElement, JSXBase } from "@stencil/core/internal";
export namespace Components {
    interface DeButton {
        /**
          * @default 'md'
         */
        "size": 'sm' | 'md' | 'lg';
    }
}
declare global {
    interface HTMLDeButtonElement extends Components.DeButton, HTMLStencilElement {
    }
    var HTMLDeButtonElement: {
        prototype: HTMLDeButtonElement;
        new (): HTMLDeButtonElement;
    };
    interface HTMLElementTagNameMap {
        "de-button": HTMLDeButtonElement;
    }
}
declare namespace LocalJSX {
    interface DeButton {
        /**
          * @default 'md'
         */
        "size"?: 'sm' | 'md' | 'lg';
    }

    interface DeButtonAttributes {
        "size": 'sm' | 'md' | 'lg';
    }

    interface IntrinsicElements {
        "de-button": Omit<DeButton, keyof DeButtonAttributes> & { [K in keyof DeButton & keyof DeButtonAttributes]?: DeButton[K] } & { [K in keyof DeButton & keyof DeButtonAttributes as `attr:${K}`]?: DeButtonAttributes[K] } & { [K in keyof DeButton & keyof DeButtonAttributes as `prop:${K}`]?: DeButton[K] };
    }
}
export { LocalJSX as JSX };
declare module "@stencil/core" {
    export namespace JSX {
        interface IntrinsicElements {
            "de-button": LocalJSX.IntrinsicElements["de-button"] & JSXBase.HTMLAttributes<HTMLDeButtonElement>;
        }
    }
}
