/* eslint-disable */
/* tslint:disable */
/**
 * This is an autogenerated file created by the Stencil compiler.
 * It contains typing information for all components that exist in this project.
 */
import { HTMLStencilElement, JSXBase } from "@stencil/core/internal";
export namespace Components {
    interface DeAlert {
        /**
          * @default 'Alert'
         */
        "heading": string;
    }
    interface DeButton {
        /**
          * @default 'md'
         */
        "size": 'sm' | 'md' | 'lg';
    }
}
declare global {
    interface HTMLDeAlertElement extends Components.DeAlert, HTMLStencilElement {
    }
    var HTMLDeAlertElement: {
        prototype: HTMLDeAlertElement;
        new (): HTMLDeAlertElement;
    };
    interface HTMLDeButtonElement extends Components.DeButton, HTMLStencilElement {
    }
    var HTMLDeButtonElement: {
        prototype: HTMLDeButtonElement;
        new (): HTMLDeButtonElement;
    };
    interface HTMLElementTagNameMap {
        "de-alert": HTMLDeAlertElement;
        "de-button": HTMLDeButtonElement;
    }
}
declare namespace LocalJSX {
    interface DeAlert {
        /**
          * @default 'Alert'
         */
        "heading"?: string;
    }
    interface DeButton {
        /**
          * @default 'md'
         */
        "size"?: 'sm' | 'md' | 'lg';
    }

    interface DeAlertAttributes {
        "heading": string;
    }
    interface DeButtonAttributes {
        "size": 'sm' | 'md' | 'lg';
    }

    interface IntrinsicElements {
        "de-alert": Omit<DeAlert, keyof DeAlertAttributes> & { [K in keyof DeAlert & keyof DeAlertAttributes]?: DeAlert[K] } & { [K in keyof DeAlert & keyof DeAlertAttributes as `attr:${K}`]?: DeAlertAttributes[K] } & { [K in keyof DeAlert & keyof DeAlertAttributes as `prop:${K}`]?: DeAlert[K] };
        "de-button": Omit<DeButton, keyof DeButtonAttributes> & { [K in keyof DeButton & keyof DeButtonAttributes]?: DeButton[K] } & { [K in keyof DeButton & keyof DeButtonAttributes as `attr:${K}`]?: DeButtonAttributes[K] } & { [K in keyof DeButton & keyof DeButtonAttributes as `prop:${K}`]?: DeButton[K] };
    }
}
export { LocalJSX as JSX };
declare module "@stencil/core" {
    export namespace JSX {
        interface IntrinsicElements {
            "de-alert": LocalJSX.IntrinsicElements["de-alert"] & JSXBase.HTMLAttributes<HTMLDeAlertElement>;
            "de-button": LocalJSX.IntrinsicElements["de-button"] & JSXBase.HTMLAttributes<HTMLDeButtonElement>;
        }
    }
}
